// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./../src/components/ParentLayout/AsideMenu/index.vue')['default']
    Content: typeof import('./../src/components/NaiveProvider/content/index.vue')['default']
    DialogContent: typeof import('./../src/components/NaiveProvider/content/DialogContent.vue')['default']
    Icon: typeof import('./../src/components/Icon/index.vue')['default']
    LayoutHeader: typeof import('./../src/components/ParentLayout/LayoutHeader/index.vue')['default']
    LayoutLogo: typeof import('./../src/components/ParentLayout/LayoutLogo/index.vue')['default']
    LoadingContent: typeof import('./../src/components/NaiveProvider/content/LoadingContent.vue')['default']
    MessageContent: typeof import('./../src/components/NaiveProvider/content/MessageContent.vue')['default']
    NaiveProvider: typeof import('./../src/components/NaiveProvider/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    ParentLayout: typeof import('./../src/components/ParentLayout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
