// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogContent: typeof import('./../src/components/NaiveProvider/content/DialogContent.vue')['default']
    LoadingContent: typeof import('./../src/components/NaiveProvider/content/LoadingContent.vue')['default']
    MessageContent: typeof import('./../src/components/NaiveProvider/content/MessageContent.vue')['default']
    NaiveProvider: typeof import('./../src/components/NaiveProvider/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
